version: "3"
networks:
    app-networks: null
services:
    nginx:
        image: "nginx:stable-alpine"
        container_name: "nginx_${APP_NAME}"
        ports:
            - "80:80"
        volumes:
            - ".:/var/www/html"
            - "./nginx-default.conf:/etc/nginx/conf.d/default.conf"
        depends_on:
            - php
            - mysql
        networks:
            - app-networks
    mysql:
        image: "mysql"
        container_name: "mysql_${APP_NAME}"
        restart: unless-stopped
        tty: true
        ports:
            - "${DB_PORT:-3306}:3306"
        environment:
            MYSQL_DATABASE: "${DB_DATABASE:-laravel}"
            MYSQL_USER: "${DB_USERNAME:-root}"
            MYSQL_PASSWORD: "${DB_PASSWORD:-password}"
            MYSQL_ROOT_PASSWORD: "${DB_PASSWORD:-password}"
            SERVICE_TAGS: dev
            SERVICE_NAME: mysql
        networks:
            - app-networks
    php:
        build: .
        container_name: "php_${APP_NAME}"
        user: "${UID:-1000}:${GID:-1000}"
        volumes:
            - ".:/var/www/html"
        ports:
            - "9000:9000"
        networks:
            - app-networks
    composer:
        image: "composer:latest"
        container_name: "composer_${APP_NAME}"
        volumes:
            - ".:/var/www/html"
        working_dir: /var/www/html
        networks:
            - app-networks
    npm:
        image: "node:18-alpine"
        container_name: "npm_${APP_NAME}"
        volumes:
            - ".:/var/www/html"
        working_dir: /var/www/html
        networks:
            - app-networks
        entrypoint:
            - npm
